//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCRTHINGEE
{
    using System.Collections.Generic;
    
    public partial class item
    {
        public item()
        {
            this.tradeitems = new HashSet<tradeitem>();
        }
    
        public int itemid { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<tradeitem> tradeitems { get; set; }
    }
}
