//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCRTHINGEE
{
    using System;

    public partial class tradeitem
    {
        public long ProductsID { get; set; }
        public int stationid { get; set; }
        public int itemid { get; set; }
        public Nullable<int> buyprice { get; set; }
        public Nullable<int> sellprice { get; set; }
        public Nullable<int> supply { get; set; }
        public Nullable<System.DateTime> lastupdate { get; set; }
    
        public virtual item item { get; set; }
        public virtual station station { get; set; }


        public override string ToString()
        {
            return "ProductsID:" + ProductsID + " stationId:" + stationid + " itemid:" + itemid + " buyprice:" +
                   buyprice + " sellprice:" + sellprice + " supply:" + supply;
        }
    }
}
